<?php

/**
 * @file
 * Module file for Missing Integrity Quiz Module.
 */

/**
 * Implements hook_menu().
 */

function missing_integrity_menu() {
  $items = array();
  $items['admin/config/content/missing_integrity'] = array(
    'title' => 'Missing Integrity Quiz Settings',
    'description' => 'Module settings page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('missing_integrity_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'missing_integrity.pages.inc',
  );
  $items['admin/missing_integrity/results'] = array(
    'page callback' => 'missing_integrity_get_results',
    'page arguments' => array(NULL, TRUE),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/missing_integrity/download'] = array(
    'page callback' => 'missing_integrity_downloadCSV',
    'page arguments' => array(NULL, TRUE),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    #'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_block_info
 */

function missing_integrity_block_info() {
  $blocks['missing_integrity'] = array(
    'info' => t('Missing Integrity Quiz Block'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

/*
 * Returns drupal view with list of students missing integrity quiz
 */

function missing_integrity_get_results () {
  
  /* Get all students who are missing integrity quiz result */
  
  $missing = missing_integrity_getMissing();
  $incomplete_emails = '';
  
  foreach($missing as $key => $value) {
      $incomplete_emails .= $value->email . '+';  
  }
  
  /*
   * Remove characters from beginning and end of $incomplete_emails string
   */
  
  $emails = substr($incomplete_emails, 1, -1);
  
  
  /*Load filtered Recent Integrity Table filtered view */
  
  $view = views_get_view('recent_integrity_table');
  $view->init();
  
  /*
   * Set contextual arguments for the view
   * Filters for only emails that have not completed the academic integrity quiz
   */
  
  $view->set_arguments(array($emails));
  $view->set_display('block_1');
  $view->pre_execute();
  $view->execute();
  $content = $view->render();
  $view->destroy();
  return  $content;
  
}

/*
 * Gets students with missing integrity quiz and provides object array
 * for other functions
 */

function missing_integrity_getMissing() {
  $full_stu_list = views_get_view_result('recent_integrity_table', 'page');
  $completed_quiz = views_get_view_result('quiz_results', 'page', '501');
  
    
  $usernames = [];
  $incomplete = [];
  
  /*
   * Build array of usernames/email address of
   * students who have completed quiz successfully
   */
  
  foreach($completed_quiz as $key => $value) {
    $usernames[] = $value->users_quiz_node_results_name;
  }
  
  foreach($full_stu_list as $key => $value) {
    if(!in_array($value->email, $usernames)){
      $incomplete[] = $value;  
    }
  }
  
  /* Return array of student objects who have not compelted quiz */
  
  return $incomplete; 
  
}


/*
 * Provides a downloadable version of the missing students report.
 */

function missing_integrity_downloadCSV() {
  
  /*
   * Get missing students via getMissing()
   */
  
  $missing = missing_integrity_getMissing();
  
  /*
   * Create downloadable CSV doc and add students to it
   */
    
  $download_file = fopen("sites/all/modules/custom/missing_integrity/files/missing_student_report.csv", "w") or die("Unable to open file!");
    
  fputcsv($download_file, array('Emails', 'First Name', 'Last Name'));
    
  foreach($missing as $key => $value) {
     $row_array = array($value->email, $value->recent_integrity_table_firstname, $value->recent_integrity_table_lastname);
     fputcsv($download_file, $row_array);  
  }
  
  /*
   * Close file and make it available for download
   */
    
  fclose($download_file);
  header("Content-type: text/csv");
  header("Content-disposition: attachment; filename = report.csv");
  readfile("sites/all/modules/custom/missing_integrity/files/missing_student_report.csv");
    
}

