<?php

/**
 * @file
 * Module file for Missing Integrity Quiz Module.
 */

/**
 * Implements hook_menu().
 */

function missing_integrity_menu() {
  $items = array();
  $items['admin/config/content/missing_integrity'] = array(
    'title' => 'Missing Integrity Quiz Settings',
    'description' => 'Module settings page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('missing_integrity_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'missing_integrity.pages.inc',
  );
  $items['admin/missing_integrity/results'] = array(
    'page callback' => 'missing_integrity_get_results',
    'page arguments' => array(NULL, TRUE),
    'access callback' => 'user_access',
    'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_block_info
 */

function custom_module_block_info() {
  $blocks['missing_integrity'] = array(
    'info' => t('Missing Integrity Quiz Block'),
    'cache' => DRUPAL_CACHE_PER_PAGE,
  );
  return $blocks;
}

function missing_integrity_get_results () {
  
  /* 
   * Get result of current Recent Integrity Table view
   * Recent Integrity Table view is generated via Data and Feeds module
   * Shows list of all students for the semester
   */
  
  $full_stu_list = views_get_view_result('recent_integrity_table', 'page');
  $completed_quiz = views_get_view_result('quiz_results', 'page', '501');
  
  $usernames = [];
  $incomplete_emails = '';
  
  /*
   * Build array of usernames/email address of
   * students who have completed quiz successfully
   */
  
  foreach($completed_quiz as $key => $value) {
    $usernames[] = $value->users_quiz_node_results_name;
  }
  
  /*
   * Check recent_integrity_table view against list of usernames that have completed quiz
   * If not in the array, add to $incomplete_emails string
   */
  
  foreach($full_stu_list as $key => $value) {
    if(!in_array($value->email, $usernames)){
      $incomplete_emails .= $value->email . '+';  
    }
  }
  
  /*
   * Remove characters from beginning and end of $incomplete_emails string
   */
  
  $emails = substr($incomplete_emails, 1, -1);
  
  
  /*Load filtered Recent Integrity Table filtered view */
  
  $view = views_get_view('recent_integrity_table', 'filtered_page' );
  $view->init();
  
  /*
   * Set contextual arguments for the view
   * Filters for only emails that have not completed the academic integrity quiz
   */
  
  $view->set_arguments(array($emails));
  $view->set_display('block_1');
  $view->pre_execute();
  $view->execute();
  $content = $view->render();
  $view->destroy();
  return  $content;
  
}